{% set version = "0.10.4" %}
{% set sha256 = "cedda80496dca8236b8196c59079873ecd902b4e810c33987cc0d86fdf55f5e7" %}

package:
  name: ipyleaflet
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ipyleaflet/ipyleaflet-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - jupyter
  run:
    - python
    - ipywidgets >=7.0.0,<8.0.0
    - traittypes >=0.2.1,<0.3.0
    - xarray >=0.10.0
    - branca >=0.3.1,<0.4.0
    - geopandas >=0.5.0,<0.6.0

test:
  imports:
    - ipyleaflet

about:
  home: https://github.com/jupyter-widgets/ipyleaflet
  license: MIT
  summary: A Jupyter widget for dynamic Leaflet maps
  doc_url: http://ipyleaflet.readthedocs.io
  dev_url: https://github.com/jupyter-widgets/ipyleaflet

extra:
  recipe-maintainers:
    - SylvainCorlay
    - ellisonbg
    - jasongrout
    - martinRenou
