{% set version = "0.5.0" %}
{% set sha256 = "159c141b937adf322673d8531524e572aa1beee782204e2d7ca8f9fefe98c796" %}

package:
    name: ipyleaflet
    version: {{ version }}

source:
    fn: ipyleaflet-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/i/ipyleaflet/ipyleaflet-{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
        - jupyter
    run:
        - python
        - ipywidgets >=7.0.0,<8.0.0

test:
    imports:
        - ipyleaflet

about:
    home: https://github.com/ellisonbg/ipyleaflet
    license: MIT
    summary: A Jupyter widget for dynamic Leaflet maps

extra:
  recipe-maintainers:
    - SylvainCorlay
    - ellisonbg
    - jasongrout
