{% set name = "ipyleaflet" %}
{% set version = "0.20.0" %}

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 098f317dd63c4bcac5176d5b78d40d5758c623f7cd013f0d0c9d7a70cefcdb34
    folder: ipyleaflet
  - url: https://pypi.org/packages/source/j/jupyter_leaflet/jupyter_leaflet-{{ version }}.tar.gz
    sha256: ad826dd7976a2b6d8b91d762c25a69a44f123b7b3bd1acaba236bd9af8e68cb4
    folder: jupyter_leaflet

build:
  number: 0
  skip: true  # [py<38]

requirements:
  host:
    - python

outputs:
  - name: jupyter_leaflet
    version: {{ version }}
    build:
      script: cd jupyter_leaflet && python -m pip install . --no-deps --no-build-isolation -vv
    requirements:
      host:
        - python
        - pip
        - nodejs
        - hatch-jupyter-builder >=0.8.1
        - hatchling
        - jupyterlab >=4,<5
        - hatch-nodejs-version >=0.3.2
    test:
      imports:
        - jupyter_leaflet
      requires:
        - python
        - pip
      commands:
        - pip check
        - test -f ${PREFIX}/share/jupyter/nbextensions/jupyter-leaflet/extension.js  # [unix]
        - test -f ${PREFIX}/share/jupyter/nbextensions/jupyter-leaflet/index.js  # [unix]
        - test -f ${PREFIX}/share/jupyter/labextensions/jupyter-leaflet/package.json  # [unix]
        - if not exist %PREFIX%\\share\\jupyter\\nbextensions\\jupyter-leaflet\\extension.js (exit 1)  # [win]
        - if not exist %PREFIX%\\share\\jupyter\\nbextensions\\jupyter-leaflet\\index.js (exit 1)  # [win]
        - if not exist %PREFIX%\\share\\jupyter\\labextensions\\jupyter-leaflet\\package.json (exit 1)  # [win]
  - name: ipyleaflet
    version: {{ version }}
    build:
      script: cd ipyleaflet && python -m pip install . --no-deps --no-build-isolation -vv
    requirements:
      host:
        - python
        - pip
        - hatchling
      run:
        - python
        - ipywidgets >=7.6.0,<9
        - traittypes >=0.2.1,<0.3.0
        - xyzservices >=2021.8.1
        - branca >=0.5.0
        - {{ pin_subpackage('jupyter_leaflet', max_pin='x.x') }}
      test:
        requires:
          - python
          - pip
        imports:
          - ipyleaflet
        commands:
          - pip check

about:
  home: https://github.com/jupyter-widgets/ipyleaflet
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Jupyter / Leaflet bridge enabling interactive maps in the Jupyter notebook.
  description: |
    Ipyleaflet is a Jupyter widget for Leaflet.js , enabling interactive maps in the Jupyter notebook.
    Every object in ipyleaflet (including the Map, TileLayers, Layers, Controls, etc.) is interactive:
    you can dynamically update attributes from Python or from the browser.
  doc_url: https://ipyleaflet.readthedocs.io
  dev_url: https://github.com/jupyter-widgets/ipyleaflet

extra:
  recipe-maintainers:
    - SylvainCorlay
    - ellisonbg
    - jasongrout
    - martinRenou
    - davidbrochart
