{% set version = "0.16.0" %}
{% set sha256 = "e702d91cef608f67dd98e04d637367e5559e42541da81288c7d52068b082beaa" %}

package:
  name: ipyleaflet
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ipyleaflet/ipyleaflet-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 4
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - nodejs >=16
  host:
    - python >=3.6
    - pip
    - jupyter
    - jupyterlab =3
    - jupyter-packaging =0.7
  run:
    - python >=3.6
    - ipywidgets >=7.6.0,<8.0.0
    - traittypes >=0.2.1,<0.3.0
    - xyzservices >=2021.8.1

test:
  imports:
    - ipyleaflet
  commands:
    - test -f ${PREFIX}/share/jupyter/nbextensions/jupyter-leaflet/extension.js                             # [unix]
    - test -f ${PREFIX}/share/jupyter/nbextensions/jupyter-leaflet/index.js                                 # [unix]
    - test -f ${PREFIX}/share/jupyter/labextensions/jupyter-leaflet/package.json                            # [unix]
    - if not exist %PREFIX%\\share\\jupyter\\nbextensions\\jupyter-leaflet\\extension.js (exit 1)           # [win]
    - if not exist %PREFIX%\\share\\jupyter\\nbextensions\\jupyter-leaflet\\index.js (exit 1)               # [win]
    - if not exist %PREFIX%\\share\\jupyter\\labextensions\\jupyter-leaflet\\package.json (exit 1)          # [win]

about:
  home: https://github.com/jupyter-widgets/ipyleaflet
  license: MIT
  license_file: LICENSE
  summary: A Jupyter widget for dynamic Leaflet maps
  doc_url: http://ipyleaflet.readthedocs.io
  dev_url: https://github.com/jupyter-widgets/ipyleaflet

extra:
  recipe-maintainers:
    - SylvainCorlay
    - ellisonbg
    - jasongrout
    - martinRenou
    - davidbrochart
