{% set version = "0.5.4" %}
{% set sha256 = "2feabb4823419c064d9eb0c842e249b4778d931a7b978dfa20afcf45f03436be" %}

package:
    name: ipyleaflet
    version: {{ version }}

source:
    fn: ipyleaflet-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/i/ipyleaflet/ipyleaflet-{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
        - jupyter
    run:
        - python
        - ipywidgets >=7.0.0,<8.0.0

test:
    imports:
        - ipyleaflet

about:
    home: https://github.com/ellisonbg/ipyleaflet
    license: MIT
    summary: A Jupyter widget for dynamic Leaflet maps

extra:
  recipe-maintainers:
    - SylvainCorlay
    - ellisonbg
    - jasongrout
