{% set version = "0.13.4" %}
{% set js_version = "0.13.3" %}
{% set sha256 = "302a9ee7f80884e58f429fa51767de5aef7a8725eac97cd17041ad7d9269f6b7" %}

package:
  name: ipyleaflet
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ipyleaflet/ipyleaflet-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - jupyter
  run:
    - python
    - ipywidgets >=7.5.0,<8.0.0
    - traittypes >=0.2.1,<0.3.0
    - branca >=0.3.1,<0.5.0
    - shapely

test:
  imports:
    - ipyleaflet
  commands:
    - test -f ${PREFIX}/share/jupyter/nbextensions/jupyter-leaflet/extension.js                                        # [unix]
    - test -f ${PREFIX}/share/jupyter/nbextensions/jupyter-leaflet/index.js                                            # [unix]
    - test -f ${PREFIX}/share/jupyter/lab/extensions/jupyter-leaflet-{{ js_version }}.tgz                              # [unix]
    - if exist %PREFIX%\\share\\jupyter\\nbextensions\\jupyter-leaflet\\extension.js (exit 0) else (exit 1)            # [win]
    - if exist %PREFIX%\\share\\jupyter\\nbextensions\\jupyter-leaflet\\index.js (exit 0) else (exit 1)                # [win]
    - if exist %PREFIX%\\share\\jupyter\\lab\\extensions\\jupyter-leaflet-{{ js_version }}.tgz (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/jupyter-widgets/ipyleaflet
  license: MIT
  license_file: LICENSE
  summary: A Jupyter widget for dynamic Leaflet maps
  doc_url: http://ipyleaflet.readthedocs.io
  dev_url: https://github.com/jupyter-widgets/ipyleaflet

extra:
  recipe-maintainers:
    - SylvainCorlay
    - ellisonbg
    - jasongrout
    - martinRenou
    - davidbrochart
