appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: rdCT4EFQHbkaPk1AlxXOXSq3LH+N3AoDhNVbOAMe7sGbdBG4xaV8TmtXRHDUWD/LT7oVYZtrxSnmxolOMI9eqFq1N0/fcL+7G687pNaJQ6Efg8ox5crazwAr0OuiQDXnUnieJPDJOSlNRSTk3nXNW9lEXbxbEYoYgmatekN4uYTEuCri0V8DSQWbybz/JYftjY9IZYNFxbX0MIIt/iYtiOku6M8rx4fHSNSHLVkGtYY16RV8UIExahYQkCMuqGEXpoFzKf9KXpnrnwC8R2v/69kWfBgcl8JPHW/3jG0os2rhdF2j7/khWglPPh5YDTdgFWNUXA86qNsU2GcHqRetkUrYcmayOmkd3aXGKY5MNmCdnqQpZe5kuYiW+Ji+A1lBDb+7XgA3bgMZo1n+i8Z6vlI1v1V5PZTA9aL2dQQChuwzqGdLg7qr0qwKH3JvIjEaQ3xkxW6hfcgg9mYezMnXy+fOn1q/PtomW6k341bKSArSv8MyiMJidanGu0C5DYDFqkViElTvsPsl/UtrmUodpZjICdRa5tY7zOIkSmn6MertdAorNae3XiVUvY6X/hIPy6MMSHBooWNQDDJEa7AQs9TfB8efyUDSeJOlVBCdm1OeovbCF9+AkRS/QunQOi2TnrIy9ohHStUUq/NulyTDXNIxFddkjkWLcNJI8VJIenI=}
