travis:
  secure:
    BINSTAR_TOKEN: ZG/2IKOL5WDBjuJU9fxcKVf/S76oKYCFXND/cNBVCNmNLMuLdpsRiq+XmJUgStyYYQfz4PD+pI0zCp6r6PfdgLRlS7/IUMxzSJIkO1in25emvVGh5q6pv51Hk/S49TD3PCArvRmCAOdhDYg6L2eNlo3sAjw1I1tgkmbjarJk266IKpSw+y9ju5CLAzWVXygWl2adcU7tTWdfOFyiPnNQa2Q6thAwTHlUqQluiySnln2hboyMJB7xC0fSX+3pNcCnzBBX6MbaAAx8l4gKbv6T/zPdSXCLMli7Ysq4FEnZhyC+enA/rzDzFOWgTMTLK8W6ReK01i5W3fq5/n8GCpk28e687OHUaUnXG3ck4TJZJOzB/rn8utYgSdB0l+7TcGa+xs7A8sOxMNyuFa0LmgVDxyU0Nkkn2PhjwPvN0UykkWEnS0qcsojP0NLe/qDVV8GIMHXCEVdXNLISZvJBDfCUpMTdxOoEZb3eGVJ6mxduaAakNnuIpCtc2YW20jteKYbsHl7U0niLsBZVp+ekxh4yS2PgjLRW8/QlttPj5N92yGCz7GtPcMRgrjURLvQ9exHWWXhl7WjQRPooYTZqHMudkTaFbSO6Mo/3N4ZKB3dcyulYVteKYGqymfcuRW9g9So3gBnn8uceFgm1CBiPze9bi7Ao7pnUNa3Prrcbo2x3/5Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
